# Metadata
sonar.projectKey=stationery-management-system
sonar.projectName=Stationery System
sonar.projectVersion=1.0

# Paths
sonar.sources=auth-service/src/main,inventory-service/src/main,request-service/src/main,frontend/src
sonar.tests=auth-service/src/test,inventory-service/src/test,request-service/src/test
sonar.java.binaries=auth-service/target/classes,inventory-service/target/classes,request-service/target/classes

# Exclusions
sonar.exclusions=**/node_modules/**,**/target/**,**/*.css,**/*.png,**/*.jpg

# Encoding
sonar.sourceEncoding=UTF-8
